export const GET_GAMES_BEGIN = "GET_GAMES_BEGIN"
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS"
export const GET_GAMES_FAIL = "GET_GAMES_FAIL"

export const GET_GAMES_BY_SEARCH_BEGIN = "GET_GAMES_BY_SEARCH_BEGIN"
export const GET_GAMES_BY_SEARCH_SUCCESS = "GET_GAMES_BY_SEARCH_SUCCESS"
export const GET_GAMES_BY_SEARCH_FAIL = "GET_GAMES_BY_SEARCH_FAIL"

export const GET_GAMES_BY_ID_BEGIN = "GET_GAMES_BY_ID_BEGIN"
export const GET_GAMES_BY_ID_SUCCESS = "GET_GAMES_BY_ID_SUCCESS"
export const GET_GAMES_BY_ID_FAIL = "GET_GAMES_BY_ID_FAIL"